name: CD

on:
  push:
    tags:
    - '*'

jobs:
  CD:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: MSBuild /t:SByteDev_MvvmCross_Plugins_WebBrowser /p:Configuration=Release
      
    - name: Upload to NuGet
      run: dotnet nuget push SByteDev.MvvmCross.Plugins.WebBrowser/bin/Release/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
    
    - name: Create GitHub Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: false
